openapi: 3.0.3
info:
  title: Uber  payment
  version: 1.0.0
servers:
  - url: https://business.zaakpay.com
  - url: https://api.zaakpay.com
  - url: https://business.uber.com
tags: []
paths:
  /merchant/dashboard/u4b/v2/registration:
    post:
      summary: Merchant registration
      operationId: registerMerchant
      tags: []
      responses:
        '200':
          description: Success
  /uber/v2/registration:
    get:
      summary: Uber registration
      operationId: getUberRegistration
      tags: []
      responses:
        '200':
          description: Success
  /uber/payment/billing:
    get:
      summary: Uber payment billing
      operationId: getUberPaymentBilling
      tags: []
      responses:
        '200':
          description: Success
  /gateway/payments/v1/config/{merchantId}:
    get:
      summary: Get payment gateway configuration
      operationId: getPaymentConfig
      tags: []
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /gateway/payments/v1/details/{merchantId}:
    get:
      summary: Get payment details
      operationId: getPaymentDetails
      tags: []
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /gateway/payments/v1/submit/{merchantId}:
    post:
      summary: Submit payment
      operationId: submitPayment
      tags: []
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /dashboard/_events:
    post:
      summary: Dashboard events
      operationId: dashboardEvents
      tags: []
      responses:
        '200':
          description: Success
  /dashboard/_translations:
    get:
      summary: Dashboard translations
      operationId: getDashboardTranslations
      tags: []
      responses:
        '200':
          description: Success
  /dashboard/graphql:
    post:
      summary: GraphQL endpoint for dashboard
      operationId: dashboardGraphql
      tags: []
      responses:
        '200':
          description: Success
  /dashboard/udi-meta:
    get:
      summary: Dashboard UDI metadata
      operationId: getDashboardUdiMeta
      tags: []
      responses:
        '200':
          description: Success
  /cdn-cgi/rum:
    post:
      summary: CDN real user metrics
      operationId: cdnRum
      tags: []
      responses:
        '200':
          description: Success
components:
  schemas: {}
