openapi: 3.0.3
info:
  title: Uber Eats App
  version: 1.0.0

servers:
  - url: https://www.uber.com

tags:
  - name: getCurrentUser
  - name: getExperiments
  - name: getBlockExperiments
  - name: isWebview
  - name: v3

paths:
  /api/getCurrentUser:
    post:
      tags: [getCurrentUser]
      summary: Get current user
      operationId: post_api_getCurrentUser
      parameters:
        - name: localeCode
          in: query
          schema:
            type: string
          example: en
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetCurrentUserPostRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object

  /api/getExperiments:
    post:
      tags: [getExperiments]
      summary: Get experiments
      operationId: post_api_getExperiments
      parameters:
        - name: localeCode
          in: query
          schema:
            type: string
          example: en
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetExperimentsPostRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object

  /api/getBlockExperiments:
    post:
      tags: [getBlockExperiments]
      summary: Get block experiments
      operationId: post_api_getBlockExperiments
      parameters:
        - name: localeCode
          in: query
          schema:
            type: string
          example: en
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetBlockExperimentsPostRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object

  /api/isWebview:
    post:
      tags: [isWebview]
      summary: Check if webview
      operationId: post_api_isWebview
      parameters:
        - name: localeCode
          in: query
          schema:
            type: string
          example: en
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IsWebviewPostRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object

  /api/v3/ip.json:
    post:
      tags: [v3]
      summary: IP telemetry
      operationId: post_api_v3_ip_json
      parameters:
        - name: referrer
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: string
        - name: page_title
          in: query
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V3PostRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    GetCurrentUserPostRequest:
      type: object
      additionalProperties: true

    IsWebviewPostRequest:
      type: object
      additionalProperties: true

    V3PostRequest:
      type: object
      required: [src, auth]
      properties:
        src:
          type: string
        auth:
          type: string

    GetExperimentsPostRequest:
      type: object
      required: [xpParameter]
      properties:
        xpParameter:
          type: object
          required: [defaultValue, key, namespace]
          properties:
            defaultValue:
              type: string
            key:
              type: string
            namespace:
              type: string

    GetBlockExperimentsPostRequest:
      type: object
      required: [geo, xpBlockKeys]
      properties:
        xpBlockKeys:
          type: array
          items:
            type: string
        geo:
          type: object
          required: [best, url, user]
          properties:
            best:
              type: object
              properties:
                localeCode: { type: string }
                countryCode: { type: string }
                territoryId: { type: integer }
                territoryName: { type: string }
                territorySlug: { type: string }
                territoryGeoPoint:
                  type: object
                  properties:
                    latitude: { type: number }
                    longitude: { type: number }
            url:
              type: object
              properties:
                localeCode: { type: string }
                countryCode: { type: string }
            user:
              type: object
              properties:
                expiresAt: { type: string, format: date-time }
                countryCode: { type: string }
                territoryId: { type: integer }
                productGeofenceUUID: { type: string }
                localeCode: { type: string }
                geoIpCoordinates:
                  type: object
                  properties:
                    lat: { type: number }
                    lng: { type: number }
                territoryGeoPoint:
                  type: object
                  properties:
                    latitude: { type: number }
                    longitude: { type: number }
                territoryGeoJson:
                  type: array
                  items:
                    type: object
                    properties:
                      lat: { type: number }
                      lng: { type: number }
